# Generated by Django 5.2.7 on 2025-10-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='loaction',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='principle',
            new_name='principal',
        ),
    ]
