# Generated by Django 5.2.7 on 2025-10-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='text',
            field=models.TextField(),
        ),
    ]
